### ISSUE TITLE
RankMatch seems to be broken

### ISSUE THREAD

**Issue by franchb** [lithammer/fuzzysearch#23]
README.md says:

```go
fuzzy.RankMatch("kitten", "sitting") // 3
```

But `RankMatch` returns `-1` always.

```go
package main

import (
	"fmt"

	"github.com/lithammer/fuzzysearch/fuzzy"
)

func main() {
	src := "kitten"
	target := "sitting"
	m := fuzzy.RankMatch(src, target)
	fmt.Println(m)
}
```
`-1`

https://play.golang.org/p/llP1davLYrK

**Comment by lithammer** [comment]
Hmm, will need to dig into this. But I suspect that the README just needs to be updated, "kitten" doesn't even match "sitting" as per `fuzzy.Match("kitten", "sitting")`.

**Comment by lithammer** [comment]
The number `3` comes from the Levenshtein between them. But since they don't match, it shouldn't be returned.

**Comment by lithammer** [comment]
I've updated the README with correct values now (see GH-24).
