### ISSUE TITLE
Unecessary alocations due to transformer.Nop

### ISSUE THREAD

**Issue by harrison3000** [lithammer/fuzzysearch#36]
I noticed that when doing Match with no normalization or folding the nop transformer does a unecessary roundtrip string -> []byte -> string, this results in 2 allocations, in my case these 2 allocs per operation end up taking 40% of the CPU time and adding a lot of GC pressure

I made a patch that fixes the issue by avoiding the transform.Nop (all tests passed, and the benchmarks confirmed 0 allocs)
[noallocnop.txt](https://github.com/lithammer/fuzzysearch/files/8586732/noallocnop.txt)

**Comment by lithammer** [comment]
Thanks for this! Never realised that `transform.Nop` did allocations. Aiming to have a release out today (UTC+2).

**Comment by lithammer** [comment]
Just released [v1.1.4](https://github.com/lithammer/fuzzysearch/releases/tag/v1.1.4).
